name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: windows-latest # can by any, just picked windows

    # this is the same as the build workflow, up until artifact upload + publish
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '10.15.1'
    - name: Restore tools
      run: dotnet tool restore
    - name: install VSCE globally
      run: dotnet fake build -t InstallVSCE
    - name: Run Test
      run: dotnet fake build -t BuildPackage
    - name: upload artifact package
      uses: actions/upload-artifact@v2
      with:
        name: ionide-fsharp-vscode-ext
        path: release/
    - name: Publish Release
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
        github-user: Krzysztof-Cieslak
        github-pw: ${{ secrets.USER_TOKEN }}
        vsce-token: ${{ secrets.VSCE_TOKEN }}
        user-email: "krzysztof_cieslak@windowslive.com"
      run: dotnet fake build -t Release
